name: Build & Deploy to EC2

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:latest ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:${{ github.ref_name }}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:${{ github.ref_name }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop app || true
          docker rm app || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:${{ github.ref_name }}
          docker run -d -p 80:3000 --restart always --name app ${{ secrets.DOCKER_USERNAME }}/final-project-portfolio:${{ github.ref_name }}
